name: PR-Lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [lint-ci]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Identify Changes
        id: vars
        run: |
          git fetch origin main --depth=1
          FILES=$(git diff --name-only origin/main...HEAD)
          echo "Files: $FILES"
          VALID=""
          for FILE in $FILES; do
            FOLDER=$(echo "$FILE" | cut -d/ -f1)
            if [ -d "$FOLDER" ] && [ -f "$FOLDER/package.json" ]; then
              if [[ ! "$VALID" =~ "$FOLDER" ]]; then
                VALID="$VALID $FOLDER"
              fi
            fi
          done
          echo "folders=$VALID" >> $GITHUB_OUTPUT

      - name: Run Tools
        if: steps.vars.outputs.folders != ''
        run: |
          for FOLDER in ${{ steps.vars.outputs.folders }}; do
            cd $FOLDER
            npm ci
            npm run lint
            npm run test
            cd ..
          done